# Book settings
title: Applied Machine Learning
author: Petri Välisuo
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

repository:
    url : https://github.com/pevalisuo/AML.git
    path_to_book : book
    brach : master

launch_buttons:
    notebook_interface : "classic" # "jupyterlab" or "classic"
    jupyterhub_url: "https://notebooks.csc.fi/#/blueprint/d1fe6e08032e4c17a0f9e0e222414598"

execute:
  exclude_patters:
    - NeuralNetworks
    
    
